// <auto-generated />
using BrainLogic.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace test_assignment.Migrations
{
    [DbContext(typeof(LocalUserContext))]
    [Migration("20241217095153_HistoryMigration")]
    partial class HistoryMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("App.Machine.Entities.Bet", b =>
                {
                    b.Property<int>("BetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("BetID");

                    b.HasIndex("UserID");

                    b.ToTable("Bet");
                });

            modelBuilder.Entity("App.Machine.Entities.Combination", b =>
                {
                    b.Property<int>("CombinationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CombinationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("CombinationID");

                    b.HasIndex("UserID");

                    b.ToTable("Combinations", (string)null);
                });

            modelBuilder.Entity("App.Machine.Entities.SpinResult", b =>
                {
                    b.Property<int>("SpinResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpinRow")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("SpinResultId");

                    b.HasIndex("UserID");

                    b.ToTable("SpinResult");
                });

            modelBuilder.Entity("App.Machine.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("App.Machine.Entities.Bet", b =>
                {
                    b.HasOne("App.Machine.Entities.User", null)
                        .WithMany("UserBets")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("App.Machine.Entities.Combination", b =>
                {
                    b.HasOne("App.Machine.Entities.User", null)
                        .WithMany("Combinations")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("App.Machine.Entities.SpinResult", b =>
                {
                    b.HasOne("App.Machine.Entities.User", null)
                        .WithMany("SpinResults")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("App.Machine.Entities.User", b =>
                {
                    b.Navigation("Combinations");

                    b.Navigation("SpinResults");

                    b.Navigation("UserBets");
                });
#pragma warning restore 612, 618
        }
    }
}
